### ISSUE TITLE
asset.burn does not seem to be working

### ISSUE THREAD

**Issue by botnumberseven** [OriginTrail/dkg.py#16]
I'm trying to burn an asset I previously published using asset.burn, but it throws an exception.
I can get this asset though.
I'm calling it just by the UAL like this - dkg.asset.burn(ual='did:dkg:otp/0x5cAC41237127F94c2D21dAe0b14bFeFa99880630/591752')
Am I using it the wrong way? Or is it actually bugged?

![image](https://github.com/OriginTrail/dkg.py/assets/42500494/075a075c-e846-4a18-b7a6-2e1d96a7ded5)

NODE INFO RECEIVED
{'version': '6.0.14'}

**asset.get as dkg.asset.get(ual='did:dkg:otp/0x5cAC41237127F94c2D21dAe0b14bFeFa99880630/591752')**
{'operation': {'publicGet': {'operationId': '5f885f33-01f6-480d-8290-0432bbd789da', 'status': 'COMPLETED'}}, 'public': {'assertion': '<uuid:1> <http://schema.org/message> "pub_with_47k_stake" .', 'assertionId': '0x8a320fb4b787628551bf730114983b8ae774955f9baeb853d6e1dd4e445401e8'}}

**asset.burn as dkg.asset.burn(ual='did:dkg:otp/0x5cAC41237127F94c2D21dAe0b14bFeFa99880630/591752')**
Traceback (most recent call last):
  File "/root/dkg.py/examples/test_1.py", line 98, in <module>
    res = dkg.asset.burn(ual='did:dkg:otp/0x5cAC41237127F94c2D21dAe0b14bFeFa99880630/591752')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/dkg.py/dkg/asset.py", line 316, in burn
    self._burn_asset(token_id)
  File "/root/dkg.py/dkg/module.py", line 37, in caller
    return self.manager.blocking_request(type(method.action), request_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/dkg.py/dkg/manager.py", line 58, in blocking_request
    return self.blockchain_provider.call_function(**request_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/dkg.py/dkg/providers/blockchain.py", line 106, in call_function
    gas_estimate = contract_function(**args).estimate_gas(options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/spam_test_2/lib/python3.11/site-packages/web3/contract/contract.py", line 318, in estimate_gas
    return estimate_gas_for_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/spam_test_2/lib/python3.11/site-packages/web3/contract/utils.py", line 203, in estimate_gas_for_function
    return w3.eth.estimate_gas(estimate_transaction, block_identifier)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/spam_test_2/lib/python3.11/site-packages/web3/eth/eth.py", line 293, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/spam_test_2/lib/python3.11/site-packages/web3/module.py", line 68, in caller
    result = w3.manager.request_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/spam_test_2/lib/python3.11/site-packages/web3/manager.py", line 232, in request_blocking
    return self.formatted_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/spam_test_2/lib/python3.11/site-packages/web3/manager.py", line 197, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/root/spam_test_2/lib/python3.11/site-packages/web3/manager.py", line 72, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cytoolz/functoolz.pyx", line 680, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 655, in cytoolz.functoolz.c_pipe
  File "/root/spam_test_2/lib/python3.11/site-packages/web3/_utils/contract_error_handling.py", line 126, in raise_contract_logic_error_on_revert
    raise ContractCustomError(data, data=data)
web3.exceptions.ContractCustomError: 0x4db94714dd2eed3f95b5460da544a35b7907a6db0d8681c7a1d973911d8feeef5c8009e8

**Comment by u-hubar** [comment]
Hi, @botnumberseven. Burn function only works if commit phase has failed (<3 commits after commit period has ended) during the first epoch (not possible to burn after the first epoch).

Commit phase ends after 25% of the epoch.

In local environment, **default epoch length is 6 minutes**, commit phase ends after ~1.5 minutes.
On the mainnet, **epoch length is 90 days** right now, commit phase ends after ~22.5 days.

So, the reason why your **spam_test_2** throws an error is probably because either there are >=3 commits or commit phase hasn't ended yet.

Hope this helps, closing the issue for now. If you have any other questions, feel free to reach out.

**Comment by botnumberseven** [comment]
Thanks @u-hubar. I didn't know about these 2 conditions.
Yeah, I tried to burn an asset which is older then 22.5 days and has less than 3 commits. And it was successful.

Although it's a bit surprising to see that it was the only existing burn event for 0x5cAC41237127F94c2D21dAe0b14bFeFa99880630 contract on the mainnet.
